version: '3.8'
services:
  library-backend:
    image: library:v3
    ports:
      - "8090:8080"
    container_name: library-1
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: postgres-1
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: