spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: postgres
    password: phandinhphung30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /library-service
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

#spring doc configurations
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs
  show-actuator: true
